/*
 * FreeBSD PPPoE configuration tool
 * (C)2016 Bogdan Nikolaev. All rights reserved
 * 
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 * 
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 * 
 * 
 */
 
 /*
  * This file is part of pppconf project
  * What is this file? Is header with some includes and functions declarations
  */

#include <stdio.h>
#include <stdlib.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <dirent.h>
#include <errno.h>
#include <unistd.h>
#include <string.h>


// bool type implementation
typedef int bool;
#define true 1
#define false 0
// string type implementation(without classes, only pointer to char array)
typedef char* string;

void printString(string str);
void getInput(string target);
bool isConfigDirectoryExists(string path);
int ConfigurePPP(string username, string userpassword, string adapter);

const int maxCharBuffer = 255; // Max chars count in string buffer
// Path constants
const string pathPPP = "/etc/ppp";
const string pathPPPConfig = "/etc/ppp/ppp.conf";
// And some strings
const string stringWelcome = "pppconf - FreeBSD PPPoE connection utility v1.0";
const string stringCopy = "(C)2016 Bogdan Nikolaev. This program is licensed under GNU GPL license";
const string stringPPPDirNotFound = "Directory /etc/ppp not exists, create it? Y/N";
const string stringDirNotFound = "Directory /etc/ppp not exists. Program terminated";
const string stringBadAnswer = "Invalid answer. Program terminated.";
const string stringFailedCreatePPPDir = "Failed to create PPP directory. Try run pppconf as root";
const string stringYes = "y";
const string stringNo = "n";
const string stringPPPConfNotFound = "File /etc/ppp/pppconf not exists, create it? Y/N";
const string stringEnterYourUserName = "Enter your username(given from ISP)";
const string stringEnterYourPassword = "Enter your password(given from ISP)";
const string stringEnterEthAdapter = "Enter your ethernet adapter(use ifconfig for discover your ethernet adapter name, default is sk0)";
const string stringIsConfigurationCorrect = "Is configuration correct? Y/N";
const string stringUserName = "User name: %s%s";
const string stringUserPassword = "User password: %s%s";
const string stringEthernetAdapter = "Ethernet adapter: %s%s";
const string stringSuccess = "PPPoE configurated, now you can connect using pppconf -connect";
const string stringUnsuccess = "Failed to write configuration, try run pppconf as root";
const string stringComment = "# This file is generated by pppconf \n";
const string stringCommentCopy = "# (C)2016 Bogdan Nikolaev. pppconf is licensed under GNU GPL \n";
const string stringConnectArgument = "-connect";
const string stringConnected = "Connected!";
const string stringHelp = "For connect type pppconf -connect";
const int pppDirRights = 0777;
const int succeful = 0;
const int unsucceful = -1; 
